# --- IPPO specific parameters ---
hidden_dim: 64
action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.001
standardise_returns: False
standardise_rewards: True
use_rnn: False
q_nstep: 10 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic_ns"
epochs: 4
eps_clip: 0.2
name: "ippo-smac"

t_max: 40050000

use_wd: False
weight_decay: 0.1
